### ISSUE TITLE
Problema cartina

### ISSUE THREAD

**Issue by lucabusato** [filippotessaro/unitn_finder#36]
Quando apro una cartina (sia di Povo 1 che di Povo 2) la cartina non si adatta allo schermo e non permette di uscire premendo il tasto esc, sono obbligato a premere la "X" in alto a destra.

**Comment by filippotessaro** [comment]
Sistemato il problema dell'adattamento a pagina;
Aggiunta funzione alla pressione del tasto esc => eseguo closePhoto()
Bloccato lo scroll della pagina dopo apertura della foto
