### ISSUE TITLE
Problema ricerca per corso

### ISSUE THREAD

**Issue by lucabusato** [filippotessaro/unitn_finder#38]
Se ricerco per corso inserendo "Ingegneria del Software 2" essendo questo corso tenuto da un singolo docente mi dovrebbero essere ritornati tutti i dati del prof mentre il bot mi ritorna solo: "Fabio Casati"

**Comment by stefanobaggetto** [comment]
Fixed. Ora vengono ritornati tutti i dati come da specifica
